CREATE TABLE USERS (
	USERID		int		NOT NULL IDENTITY UNIQUE,
	_USERNAME	varchar(255) NOT NULL,
	_PASSWORD	varchar(255) NOT NULL,
	PRIMARY KEY (USERID)
);

CREATE TABLE TASKS (
	TASKID		int		NOT NULL IDENTITY UNIQUE,
	USERID		int		NOT NULL,
	_TASKNAME	int		not null,
	_MINUTES	int		NOT NULL,
	_PM			BIT		NOT NULL,
	PRIMARY KEY (TASKID),
	FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);